[package]
name = "release"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "*"
serde={version="*",features=["derive"]}
zip = "*"
walkdir = "*"
[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
opt-level = "z"
